### ISSUE TITLE
Cleaning up various containers...

### ISSUE THREAD

**Issue by RussellMcOrmond** [c7a/cihm-cantaloupe#13]
We currently launch multiple containers via a docker-compose

* https://github.com/crkn-rcdr/cihm-public-cos  - Apache config that proxies to other containers
* https://github.com/crkn-rcdr/cihm-cookie-authorizer  - for setting cookies for the existing auth method
* https://github.com/crkn-rcdr/cihm-file-access - Does the lookup so that mod_xsendfile can offer file downloads
* cihm-cantaloupe

As we are using Swift for file downloads, and possibly not using domain cookies for authorisation, I'm wondering if we should clean up the configuration for or possibly stop using the Apache proxy.

**Comment by RussellMcOrmond** [comment]
As https will come up soon: https://cantaloupe-project.github.io/manual/4.1/deployment.html#SSL/TLS

Standalone mode supports SSL, but it is configured a bit differently than we have other containers.  We would need to learn how to get our keys into the right place as part of container startup (preferably using a docker volume mount to expose keys rather than putting keys in docker image).

**Comment by RussellMcOrmond** [comment]
On vbc I've removed cihm-file-access, as it can't do anything being called from a container that doesn't have the files any more...

**Comment by RussellMcOrmond** [comment]
I'll start work on this, as I'm already needing to do some cleanup.   I'll put config in the apache/ sub-directory similar to what we did with cap, and we can have a sample compose similar to what we are doing in production.  I'll leave the question about cookies to later.

**Comment by SaschaAdler** [comment]
We aren't currently using the cookie authorizer (we built it for IIIF demos related to my Access presentation a couple years back) and I think it's reasonable to remove it from the Docker config.

Once we have Cantaloupe pointing to a Swift container that only contains publicly-available access copies of images (and other, also publicly-available things, perhaps), it seems to me that any authorization questions are going to be about the object in question instead of the user in question, which changes our approach, e.g. we look up to see if the object has been taken down, but not to see if the user is allowed to see it.

**Comment by RussellMcOrmond** [comment]
I forgot to reference this issue with f18b13611633f7a6ac34ffde04def138db841493

I'm also curious what you know about the reference to  https://cantaloupe-project.github.io/manual/4.1/deployment.html#Docker about differences in how Java Heap RAM is allocated.  I've tried removing the "-Xmx16g" with 0f89707d14d0e17ae7848019f56f2b994b83d45a , but don't know if this is what we need.  It seemed to go above 16g used with that removed.

I'm still suspicious that the odd failure condition we've seen with Cantaloupe relates to memory usage, so we might want to put some thought into that.

**Comment by SaschaAdler** [comment]
The [Java release notes](https://www.oracle.com/technetwork/java/javase/8u191-relnotes-5032181.html#JDK-8146115) linked to in the Cantaloupe manual refer to changes made in the Java runtime where Java can detect it's being run in a Docker container and therefore can query and use the resources provided to the container when running. I assume this means that instead of setting the Java virtual machine's maximum heap size with `-Xmx`, Java will expand its maximum heap size to the amount of memory available in the container.

Of course, if Cantaloupe exceeds whatever the maximum heap size ends up at, it will still throw an error.

**Comment by RussellMcOrmond** [comment]
If Docker isn't given a maximum, what does that mean?  The JVM previously seemed to always have a cap even when the server had far more memory, and I never understood how to configure that.

**Comment by SaschaAdler** [comment]
[Here's the docs for Docker memory constraints](https://docs.docker.com/config/containers/resource_constraints/).

It looks like Docker does not assign limits to containers by default.

**Comment by RussellMcOrmond** [comment]
Will set up a health check #10 

Closing this issue as the number of images has been cleaned up.
