### ISSUE TITLE
Upgrade to v4.0

### ISSUE THREAD

**Issue by SaschaAdler** [c7a/cihm-cantaloupe#5]
Upgrading to v4.0 takes [a fair bit of work](https://medusa-project.github.io/cantaloupe/upgrade.html), but provides [benefits](https://medusa-project.github.io/cantaloupe/changes.html).

**Comment by SaschaAdler** [comment]
I have a working Cantaloupe 4.0.2 installation on [Romano](http://image.swiss.canadiana.ca/).

Changes are made in https://github.com/c7a/cihm-cantaloupe/commit/22f892a9b04bc1c257dde920b1ed8f43dbb92185

Russell, I'm not sure what kind of testing we should do in terms of any of the more interesting libraries and tools required to generate images (openjpeg, etc.)

**Comment by RussellMcOrmond** [comment]
Looking up some older Redmine tickets to find some interesting images to test against.

TIF No compression - http://heritage.havarti.canadiana.ca/view/oocihm.lac_reel_t11146/10
TIF RLE (lossless) - http://online.havarti.canadiana.ca/view/oocihm.8_06745_78/1
TIF Group4 (FAX, lossy) - http://online.havarti.canadiana.ca/view/oocihm.8_04385_211/2
TIF LZW (lossless) - http://numeris.havarti.canadiana.ca/view/numeris.RD_1994_FA00_034/322
TIF JPEG - http://numeris.canadiana.ca/view/numeris.RF_1993_BY00_003_1_3/14
JPEG2000 - http://online.havarti.canadiana.ca/view/oocihm.99400/1
PDF - http://numeris.havarti.canadiana.ca/view/numeris.RD_2000_SP00_001/1


I of course did a bunch of http://numeris.havarti.canadiana.ca/viewrandom and http://online.havarti.canadiana.ca/viewrandom while looking at the output of `docker logs -f cihm-cantaloupe` to see if anything odd might be happening, but it looks good to me.

If you think this is ready for the next step, let me know and I can deploy to Brie and point the production CAP to that.  Only reason to postpone is because it is a long weekend coming up, and we've had a poor history with the content server over long weekends.

**Comment by SaschaAdler** [comment]
I think we're ready to go, but I agree with postponing until next week.

**Comment by RussellMcOrmond** [comment]
I have pushed this version to Paneer (Proxy on http://image.queso.canadiana.ca ) , and after some testing pointed the primary CAP at it.   I'm fine with this version and believe we can merge with 'master' branch at any time.

**Comment by SaschaAdler** [comment]
Closed thanks to the merge above.
